export enum ErrorCode {
  // Authentication Errors
  AUTH_INVALID_OTP = 'AUTH_INVALID_OTP',
  AUTH_OTP_EXPIRED = 'AUTH_OTP_EXPIRED',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',

  // User Domain Errors
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_BLOCKED = 'USER_BLOCKED',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  // Society & Address Domain Errors
  SOCIETY_NOT_FOUND = 'SOCIETY_NOT_FOUND',
  SOCIETY_INACTIVE = 'SOCIETY_INACTIVE',
  ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
  ADDRESS_INVALID_SOCIETY = 'ADDRESS_INVALID_SOCIETY',

  // Service Domain Errors
  SERVICE_NOT_FOUND = 'SERVICE_NOT_FOUND',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',

  // Booking Domain Errors
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  BOOKING_ALREADY_CANCELLED = 'BOOKING_ALREADY_CANCELLED',
  BOOKING_CANNOT_CANCEL = 'BOOKING_CANNOT_CANCEL',
  BOOKING_SLOT_UNAVAILABLE = 'BOOKING_SLOT_UNAVAILABLE',

  // Payment & Refund Errors
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  REFUND_FAILED = 'REFUND_FAILED',
  REFUND_NOT_ELIGIBLE = 'REFUND_NOT_ELIGIBLE',

  // Vendor Domain Errors
  VENDOR_NOT_FOUND = 'VENDOR_NOT_FOUND',
  VENDOR_NOT_AVAILABLE = 'VENDOR_NOT_AVAILABLE',

  // Demand Campaign Errors
  DEMAND_CAMPAIGN_NOT_FOUND = 'DEMAND_CAMPAIGN_NOT_FOUND',
  DEMAND_THRESHOLD_FAILED = 'DEMAND_THRESHOLD_FAILED',

  // Growth & Support Errors
  REFERRAL_NOT_FOUND = 'REFERRAL_NOT_FOUND',
  REWARD_NOT_FOUND = 'REWARD_NOT_FOUND',
  COMPLAINT_NOT_FOUND = 'COMPLAINT_NOT_FOUND',

  // Common Infrastructure Errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
